# Site settings
title: My Technique Blog by Zong Chang
email: windcandle0725@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is for the introduction of new tools and techniques which have been
  used in my work, including coding, useful commands, new technologies and some
  wonderful tools and softwares.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://www.lushandyangyang.com" # the base hostname & protocol for your site
github_username:  changzong

# Build settings
markdown: kramdown
